### ISSUE TITLE
Robocop and Robocop 2

### ISSUE THREAD

**Issue by DeepLight01** [mattcurrie/gb-save-states#14]
Please make a patch for Robocop and Robocop 2

**Comment by DeepLight01** [comment]
What does it mean that it requires manual patching?
I'v looked through the code of the Robocop game and found out the joystick read routing is in bank 4. Can't stick it to be used by regular instruction variant. Did you mean that one needs to write additional code for that save to work?

**Comment by mattcurrie** [comment]
Yes, I tried my automated patch script but it fails because there are actually two joypad read functions (in bank 0 and bank 4), and they are a bit non-standard in how they handle the value that was read, so it will need some custom code to be written for it. I'll get to it eventually when I find some time :)

**Comment by DeepLight01** [comment]
Thanks! Superb! Looking forward to it!

**Comment by DeepLight01** [comment]
Could you please provide you patch script?

**Comment by mattcurrie** [comment]
Hi there,

I've now created patches for Robocop and Robocop 2. Give them a try and let me know if any issues :)

Re: the patch script, it isn't really in a releasable state at the moment and very often requires manual intervention. If I ever get it into a decent state then I'll add it to the repo.
