### ISSUE TITLE
[Request patch] Metroid II - EJRTQ Colorization

### ISSUE THREAD

**Issue by jjfreak** [mattcurrie/gb-save-states#57]
Thanks for making the patch for the Super Mario Land 3 DX!

Any chance of getting a patch for this game: https://www.romhacking.net/hacks/4388/

Thanks and keep up the good work!

Cheers 😊

**Comment by mattcurrie** [comment]
Hi,

I've created a patch for this. 

This one was a bit interesting because the colorization patch was still using MBC1 which in theory shouldn't be used for double speed mode games. I ended up having to patch some of the code to use MBC5 instead so that we can access the full 128 KB of SRAM. I've played through a bit of the game and it seems to be working fine, but it is possible there are some other MBC1 accesses that I've missed. 

Anyway give it a try and let me know if any issues.

**Comment by jjfreak** [comment]
Hi, 

Thanks for this patch, but this one I can't get it to work with the Bennvenns MBC5 patch 😥

[https://www.mediafire.com/file/q1031gc9cdfm5w0/Metroid_II_-_EJRTQ_Colorization_v1.3_-_Canon_Samus_BennVennMBC5fix.ips/file](url)

Any chance you could take a look or maybe share your MBC5 patch? 

Once again thanks a lot for all your great work! 

Cheers!

**Comment by mattcurrie** [comment]
Hey, the save state patch handles the MBC5 patching, so Bennvenn's MBC5 patch isn't needed. You should be able to just patch the original ROM with the colorisation patch and then apply the save state patch on top.
